test: &default

  # Credentials for REST APIs
  client_id: ATs2OcB45wcqfMrnVHajQ8f39CuW-Lk6Z8NIhA-KKhxyeAtYpNFyLCknKeTsoGjshtlOuu1wqNK65j2_
  client_secret: EM45y4vqRgLX3RTQobTii_6QVCuALBc_kDa0CGBl9wTl13bkaliW5hvXcMuSW8uVSaWXRdyOF7N2PxXv

  # Mode can be 'live' or 'sandbox'
  mode: sandbox

  # Credentials for Classic APIs
  app_id: APP-80W284485P519543T
  username: jb-us-seller_api1.paypal.com
  password: WX4WTU3S8MY44S7F
  signature: AFcWxV21C7fd0v3bYYYRCpSSRl31A7yDhhsPUU2XhtMoZXsWHFxu-RWy
  # # With Certificate
  # cert_path: "config/cert_key.pem"
  sandbox_email_address: karaokebar@gmail.com

  # # IP Address
  # ip_address: 127.0.0.1
  # # HTTP Proxy
  # http_proxy: http://proxy-ipaddress:3129/

development:
  <<: *default

production:
  <<: *default
  mode: live
  client_id: CLIENT_ID
  client_secret: CLIENT_SECRET